<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-10-21 11:38
=======
# Generated by Django 2.2.1 on 2019-10-07 16:00
>>>>>>> 9b82b610120eeb221305ff229c6716a158cd4807

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
<<<<<<< HEAD
=======
                ('document', models.FileField(blank=True, null=True, upload_to='announce_docs/')),
>>>>>>> 9b82b610120eeb221305ff229c6716a158cd4807
            ],
        ),
    ]
