# Generated by Django 2.2.1 on 2019-10-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='document',
        ),
    ]
