# Generated by Django 2.2.1 on 2019-09-29 06:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('flatno', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('NOC', 'NOC'), ('AddressProof', 'AddressProof'), ('SalesAgreement', 'SalesAgreement'), ('CCTV', 'CCTv'), ('Other', 'Other')], default='NOC', max_length=100)),
                ('name_to_be_addressed', models.CharField(blank=True, max_length=100)),
                ('new_members_names', models.CharField(blank=True, max_length=200)),
                ('sales_details', models.CharField(blank=True, max_length=300)),
                ('cctv_date', models.DateField(blank=True, default=datetime.date.today)),
                ('cctv_time_from', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cctv_time_to', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('request', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
