# Generated by Django 2.1.7 on 2019-09-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.DateField()),
                ('flatno', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=200)),
                ('complaint_type', models.CharField(choices=[('Intercom', 'Intercom'), ('Leakage', 'Leakage'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], default='Other', max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('flatno', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('NOC', 'NOC'), ('AddressProof', 'AddressProof'), ('SalesAgreement', 'SalesAgreement'), ('CCTV', 'CCTv'), ('Other', 'Other')], default='NOC', max_length=100)),
                ('name_to_be_addressed', models.CharField(max_length=100)),
                ('new_members_names', models.CharField(max_length=200)),
                ('sales_details', models.CharField(max_length=300)),
                ('cctv_from', models.DateTimeField()),
                ('cctv_to', models.DateTimeField()),
            ],
        ),
    ]
