# Generated by Django 2.2.1 on 2019-09-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='cctv_date',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('NOC', 'NOC'), ('AddressProof', 'AddressProof'), ('SalesAgreement', 'SalesAgreement'), ('CCTV', 'CCTV'), ('Other', 'Other')], default='NOC', max_length=100),
        ),
    ]
