# Generated by Django 2.2.1 on 2019-09-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='bank_format',
            field=models.FileField(default='noimage.jpg', upload_to='request_sales_docs/'),
        ),
    ]
