# Generated by Django 2.2.1 on 2019-10-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bank_format',
            field=models.FileField(blank=True, null=True, upload_to='request_bank_format/'),
        ),
    ]
