# Generated by Django 2.1.7 on 2019-09-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complain_img',
            field=models.ImageField(default='noimage.jpg', upload_to='complaint_images/'),
        ),
    ]
