# Generated by Django 2.2.1 on 2019-10-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20191020_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bank_format',
            field=models.FileField(null=True, upload_to='request_bank_format/'),
        ),
    ]
