# Generated by Django 2.2.1 on 2019-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190929_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='created',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='request',
            name='inprogress',
            field=models.IntegerField(default=0),
        ),
    ]
