# Generated by Django 2.1.1 on 2019-09-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_cheque_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheque_details',
            old_name='userid',
            new_name='user',
        ),
    ]
