# Generated by Django 2.2.1 on 2019-09-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_request_bank_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bank_format',
            field=models.FileField(blank=True, upload_to='request_sales_docs/'),
        ),
    ]
