# Generated by Django 2.2.1 on 2019-10-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20191002_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complain_img',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AlterField(
            model_name='landl',
            name='agreement',
            field=models.FileField(upload_to='landl_docs_agreement/'),
        ),
        migrations.AlterField(
            model_name='landl',
            name='police_ver',
            field=models.FileField(upload_to='landl_docs_police/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='bank_format',
            field=models.FileField(upload_to='request_bank_format/'),
        ),
    ]
