# Generated by Django 2.2.1 on 2019-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190930_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque_details',
            name='remarks',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='bank_format',
            field=models.FileField(default='noimage.jpg', upload_to='request_sales_docs/'),
        ),
    ]
