# Generated by Django 2.2.1 on 2019-09-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190929_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='request',
            name='created',
        ),
        migrations.RemoveField(
            model_name='request',
            name='inprogress',
        ),
    ]
