# Generated by Django 2.2.1 on 2019-09-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190929_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='request',
            name='inprogress',
            field=models.BooleanField(default=False),
        ),
    ]
