# Generated by Django 2.2.1 on 2019-09-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190930_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landl_date', models.DateField(auto_now_add=True)),
                ('flatno', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('agreement', models.FileField(default='noimage.jpg', upload_to='landl_docs/')),
                ('police_ver', models.FileField(default='noimage.jpg', upload_to='landl_docs/')),
            ],
        ),
    ]
