# Generated by Django 2.1.1 on 2019-10-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_landl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landl',
            name='agreement',
            field=models.FileField(default='noimage.jpg', upload_to='landl_docs_agreement/'),
        ),
        migrations.AlterField(
            model_name='landl',
            name='police_ver',
            field=models.FileField(default='noimage.jpg', upload_to='landl_docs_police/'),
        ),
    ]
