# Generated by Django 2.2.1 on 2019-09-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('flat_no', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=50)),
            ],
        ),
    ]
