# Generated by Django 2.2.1 on 2019-09-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='quotations/pdfs/')),
            ],
        ),
    ]
