# Generated by Django 2.2.1 on 2019-10-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
