# Generated by Django 2.2.1 on 2019-09-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='visitor_id',
        ),
    ]
