# Generated by Django 2.1.1 on 2019-10-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rights',
            field=models.CharField(default='Normal', max_length=10),
        ),
    ]
