# Generated by Django 2.2.1 on 2019-11-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rights',
            field=models.CharField(default='Admin', max_length=10),
        ),
    ]
