# Generated by Django 2.2.1 on 2019-09-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='pdf',
        ),
    ]
