# Generated by Django 2.2.1 on 2019-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191105_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rights',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
