# Generated by Django 2.2.1 on 2019-10-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usertype',
        ),
    ]
