# Generated by Django 2.2.1 on 2019-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_visitors_visitor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='id',
        ),
        migrations.AlterField(
            model_name='visitors',
            name='flat_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
