# Generated by Django 2.2.1 on 2019-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190928_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='flat_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='telephone',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
