# Generated by Django 2.2.1 on 2019-09-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_quotation_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pdf',
            field=models.FileField(default=0, upload_to='quotations/pdfs/'),
            preserve_default=False,
        ),
    ]
